nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'append', 'delete', 'entries', 'foreach', 'get', 'has', 'keys', 'set', 'values']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
