nelmio_api_doc:
    documentation:
        info:
            title: Limon API
            description: API ouverte pour les développeurs
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/movie(?!/doc$) # Accepts routes under /api except /api/doc
        with_annotation: true
